---
project: IndiaLabs
kind: PIPELINE
name: RK_ACI_Login
icon: organization,left, is-warm-grey
enabled: true
description: Script to login in to ACI APIC controller environment
concurrency: 10
output:
  APIC-cookie: ${Stage0.getTokenAPIC.output.responseJson['imdata'][0].aaaLogin.attributes.token}
workspace:
  type: DOCKER
  endpoint: ''
  image: ''
  registry: ''
  path: ''
  autoCloneForTrigger: false
  limits:
    memory: 512
    cpu: 1.0
stageOrder:
- Stage0
stages:
  Stage0:
    taskOrder:
    - getTokenAPIC
    tasks:
      getTokenAPIC:
        type: REST
        input:
          action: post
          url: https://172.16.40.15/api/aaaLogin.json
          headers:
            Accept: application/json
            Content-Type: application/json
          payload: |-
            {
              "aaaUser" : {
                "attributes" : {
                  "name" : "adminusername",
                  "pwd" : "xxpasswordxx"
                }
              }
            }
