---
project: IndiaLabs
kind: PIPELINE
name: RK_Create_ACI_Tenant
icon: organization,left, is-pink
enabled: true
description: This pipeline creates Tenant in the ACI environment
concurrency: 10
input:
  tenantAlias: ''
  tenantDescription: ''
  tenantName: ''
_inputMeta:
  tenantDescription:
    mandatory: true
    description: Please provide tenant description.
  tenantName:
    mandatory: true
    description: Please provide the name of the Tenant you want to create. No spaces allowed
  tenantAlias:
    mandatory: true
    description: Please provide Tenant Alias Name. No spaces allowed
workspace:
  type: DOCKER
  endpoint: ''
  image: ''
  registry: ''
  path: ''
  autoCloneForTrigger: false
  limits:
    memory: 512
    cpu: 1.0
  customProperties:
    proxyType: nodePort
stageOrder:
- Stage0
stages:
  Stage0:
    taskOrder:
    - getToken
    - createTenant
    tasks:
      getToken:
        type: Pipeline
        input:
          pipeline: RK_ACI_Login
          inputProperties: {
            }
      createTenant:
        type: REST
        input:
          action: post
          url: https://172.16.40.15/api/node/mo/uni/tn-${input.tenantName}.json
          headers:
            Accept: application/json
            Content-Type: application/json
            cookie: APIC-Cookie=${Stage0.getToken.output.outputProperties.APIC-cookie}
          payload: |-
            {
              "fvTenant": {
                "attributes": {
                  "dn": "uni/tn-${input.tenantName}",
                  "name": "${input.tenantName}",
                  "nameAlias": "${input.tenantAlias}",
                  "descr": "${input.tenantDescription}",
                  "rn": "tn-${input.tenantName}",
                  "status": "created"
                },
                "children": []
              }
            }
