---
project: IndiaLabs
kind: PIPELINE
name: RK_ACI_End_to_End
icon: organization,left, is-purple
enabled: true
description: This pipeline creates end to end objects of ACI environment. The objects it creates are Tenant,
  Applicaiton profile, VRF, Bridge Domains, End point Groups.
concurrency: 10
input:
  tenantName: ''
_inputMeta:
  tenantName:
    mandatory: true
    description: Please enter the Tenant Name. No spaces or special characters.
workspace:
  type: DOCKER
  endpoint: ''
  image: ''
  registry: ''
  path: ''
  autoCloneForTrigger: false
  limits:
    memory: 512
    cpu: 1.0
  customProperties:
    proxyType: nodePort
stageOrder:
- Stage0
stages:
  Stage0:
    taskOrder:
    - ACILogin
    - CreateTenant
    - CreateAppProfile
    - createVRF
    - createBridgeDomain
    - createEPG
    tasks:
      ACILogin:
        type: Pipeline
        input:
          pipeline: RK_ACI_Login
          inputProperties: {
            }
      CreateTenant:
        type: REST
        input:
          action: post
          url: https://172.16.40.15/api/node/mo/uni/tn-${input.tenantName}_tenant.json
          headers:
            Accept: application/json
            Content-Type: application/json
            cookie: APIC-Cookie=${Stage0.ACILogin.output.outputProperties.APIC-cookie}
          payload: |-
            {
              "fvTenant": {
                "attributes": {
                  "dn": "uni/tn-${input.tenantName}_tenant",
                  "name": "${input.tenantName}_tenant",
                  "nameAlias": "${input.tenantName}_alias",
                  "descr": "${input.tenantName}_description ",
                  "rn": "tn-${input.tenantName}_tenant",
                  "status": "created"
                },
                "children": []
              }
            }
      createVRF:
        type: REST
        input:
          action: post
          url: https://172.16.40.15/api/node/mo/uni/tn-${input.tenantName}_tenant.json
          headers:
            Accept: application/json
            Content-Type: application/json
            cookie: APIC-Cookie=${Stage0.ACILogin.output.outputProperties.APIC-cookie}
          payload: |-
            {
              "fvTenant": {
                "attributes": {
                  "dn": "uni/tn-${input.tenantName}_tenant",
                  "status": "modified"
                },
                "children": [
                  {
                    "fvCtx": {
                      "attributes": {
                        "dn": "uni/tn-${input.tenantName}_tenant/ctx-${input.tenantName}_VRF",
                        "name": "${input.tenantName}_VRF",
                        "nameAlias": "${input.tenantName}_VRF_Alias",
                        "descr": "${input.tenantName}_VRF_Description",
                        "pcEnfPref": "unenforced",
                        "rn": "ctx-${input.tenantName}_VRF",
                        "status": "created"
                      },
                      "children": []
                    }
                  }
                ]
              }
            }
      CreateAppProfile:
        type: REST
        input:
          action: post
          url: https://172.16.40.15/api/node/mo/uni/tn-${input.tenantName}_tenant/ap-${input.tenantName}_appProfile.json
          headers:
            Accept: application/json
            Content-Type: application/json
            cookie: APIC-Cookie=${Stage0.ACILogin.output.outputProperties.APIC-cookie}
          payload: |-
            {
              "fvAp": {
                "attributes": {
                  "dn": "uni/tn-${input.tenantName}_tenant/ap-${input.tenantName}_appProfile",
                  "name": "${input.tenantName}_appProfile",
                  "nameAlias": "${input.tenantName}_appProfile_Alias",
                  "descr": "${input.tenantName}_appProfile_Description",
                  "rn": "ap-${input.tenantName}_appProfile",
                  "status": "created"
                },
                "children": []
              }
            }
      createEPG:
        type: REST
        input:
          action: post
          url: https://172.16.40.15/api/node/mo/uni/tn-${input.tenantName}_tenant/ap-${input.tenantName}_appProfile/epg-${input.tenantName}_EPG.json
          headers:
            Accept: application/json
            Content-Type: application/json
            cookie: APIC-Cookie=${Stage0.ACILogin.output.outputProperties.APIC-cookie}
          payload: |-
            {
             "fvAEPg": {
              "attributes": {
               "dn": "uni/tn-${input.tenantName}_tenant/ap-${input.tenantName}_appProfile/epg-${input.tenantName}_EPG",
               "prio": "level3",
               "name": "${input.tenantName}_EPG",
               "nameAlias": "${input.tenantName}_EPG_Alias",
               "descr": "${input.tenantName}_EPG_Deescription",
               "rn": "epg-${input.tenantName}_EPG",
               "status": "created"
              },
              "children": [
               {
                "fvRsBd": {
                 "attributes": {
                  "tnFvBDName": "${input.tenantName}_BridgeDomain",
                  "status": "created,modified"
                 },
                 "children": []
                }
               }
              ]
             }
            }
      createBridgeDomain:
        type: REST
        input:
          action: post
          url: https://172.16.40.15/api/node/mo/uni/tn-${input.tenantName}_tenant/BD-${input.tenantName}_BridgeDomain.json
          headers:
            Accept: application/json
            Content-Type: application/json
            cookie: APIC-Cookie=${Stage0.ACILogin.output.outputProperties.APIC-cookie}
          payload: |-
            {
              "fvBD": {
                "attributes": {
                  "dn": "uni/tn-${input.tenantName}_tenant/BD-${input.tenantName}_BridgeDomain",
                  "mac": "00:22:BD:F8:19:FF",
                  "arpFlood": "true",
                  "name": "${input.tenantName}_BridgeDomain",
                  "nameAlias": "${input.tenantName}_BridgeDomain_Alias",
                  "descr": "${input.tenantName}_BridgeDomain_Description",
                  "rn": "BD-${input.tenantName}_BridgeDomain",
                  "status": "created"
                },
                "children": [
                  {
                    "fvRsCtx": {
                      "attributes": {
                        "tnFvCtxName": "${input.tenantName}_VRF",
                        "status": "created,modified"
                      },
                      "children": []
                    }
                  }
                ]
              }
            }
