---
project: IndiaLabs
kind: PIPELINE
name: RK_Create_ACI_Application_Profile
icon: organization,left, is-success
enabled: true
description: This pipeline creates application profile in the ACI environment
concurrency: 10
input:
  AppProfileAlias: ''
  AppProfileDescription: ''
  AppProfileName: ''
  tenatName: ''
_inputMeta:
  AppProfileName:
    mandatory: true
    description: Please enter application profile name without any spaces or special characters
  AppProfileAlias:
    mandatory: true
    description: Please enter Application profile alias without any space or special characters
  AppProfileDescription:
    mandatory: false
    description: Please input description for this application profile
  tenatName:
    mandatory: true
    description: Please enter existing Tenant name without space or special characters
workspace:
  type: DOCKER
  endpoint: ''
  image: ''
  registry: ''
  path: ''
  autoCloneForTrigger: false
  limits:
    memory: 512
    cpu: 1.0
stageOrder:
- Stage0
stages:
  Stage0:
    taskOrder:
    - ACILogin
    - CreateAppProfile
    tasks:
      ACILogin:
        type: Pipeline
        input:
          pipeline: RK_ACI_Login
          inputProperties: {
            }
      CreateAppProfile:
        type: REST
        input:
          action: post
          url: https://172.16.40.15/api/node/mo/uni/tn-${input.tenatName}/ap-${input.AppProfileName}.json
          headers:
            Accept: application/json
            Content-Type: application/json
            cookie: APIC-Cookie=${Stage0.ACILogin.output.outputProperties.APIC-cookie}
          payload: |-
            {
             "fvAp": {
              "attributes": {
               "dn": "uni/tn-${input.tenatName}/ap-${input.AppProfileName}",
               "name": "${input.AppProfileName}",
               "nameAlias": "${input.AppProfileAlias}",
               "descr": "manualApp_Description",
               "rn": "ap-${input.AppProfileName}",
               "status": "created"
              },
              "children": []
             }
            }
