---
project: IndiaLabs
kind: PIPELINE
name: RK_Create_ACI_vRF
icon: organization,left, is-success
enabled: true
description: This pipe line creates ACI vRF
concurrency: 10
input:
  vRFAlias: ''
  vRFDescription: ''
  vRFName: ''
  vRFTenantName: ''
_inputMeta:
  vRFAlias:
    mandatory: true
    description: Please enter vRF Alias Name without space or any special characters
  vRFDescription:
    mandatory: true
    description: Please enter a description for vRF
  vRFTenantName:
    mandatory: true
    description: Please enter vRF tenant name
  vRFName:
    mandatory: true
    description: Please enter vRF Name without spaces or special characters
workspace:
  type: DOCKER
  endpoint: ''
  image: ''
  registry: ''
  path: ''
  autoCloneForTrigger: false
  limits:
    memory: 512
    cpu: 1.0
stageOrder:
- Stage0
stages:
  Stage0:
    taskOrder:
    - ACILogin
    - createvRF
    tasks:
      ACILogin:
        type: Pipeline
        input:
          pipeline: RK_ACI_Login
          inputProperties: {
            }
      createvRF:
        type: REST
        input:
          action: post
          url: https://172.16.40.15/api/node/mo/uni/tn-${input.vRFTenantName}.json
          headers:
            Accept: application/json
            Content-Type: application/json
            cookie: APIC-Cookie=${Stage0.ACILogin.output.outputProperties.APIC-cookie}
          payload: |-
            {
              "fvTenant": {
                "attributes": {
                  "dn": "uni/tn-${input.vRFTenantName}",
                  "status": "modified"
                },
                "children": [
                  {
                    "fvCtx": {
                      "attributes": {
                        "dn": "uni/tn-${input.vRFTenantName}/ctx-${input.vRFName}",
                        "name": "${input.vRFName}",
                        "nameAlias": "${input.vRFAlias}",
                        "descr": "${input.vRFDescription}",
                        "pcEnfPref": "unenforced",
                        "rn": "ctx-${input.vRFName}",
                        "status": "created"
                      },
                      "children": []
                    }
                  }
                ]
              }
            }
