---
project: IndiaLabs
kind: PIPELINE
name: RK_Create_ACI_EPG
icon: organization,left, is-purple
enabled: true
description: This pipeline creates End Point Groups in Cisco ACI environment
concurrency: 10
input:
  AppProfile: ''
  BDname: ''
  EPGAlias: ''
  EPGDescription: ''
  EPGName: ''
  tenantName: ''
_inputMeta:
  tenantName:
    mandatory: true
    description: Please enter the existing Tenant Name without any spaces or special characters
  EPGAlias:
    mandatory: true
    description: Please enter EPG Alias without any space or special characters
  EPGName:
    mandatory: true
    description: Please enter EPG name without any space or special characters
  AppProfile:
    mandatory: true
    description: Please enter the existing application profile name without any spaces or special characters
  BDname:
    mandatory: true
    description: Please enter the existing Bridge Domain name, without any spaces or special characters
  EPGDescription:
    mandatory: true
    description: Please enter EPG description
workspace:
  type: DOCKER
  endpoint: ''
  image: ''
  registry: ''
  path: ''
  autoCloneForTrigger: false
  limits:
    memory: 512
    cpu: 1.0
stageOrder:
- Stage0
stages:
  Stage0:
    taskOrder:
    - ACILogin
    - createEPG
    tasks:
      ACILogin:
        type: Pipeline
        input:
          pipeline: RK_ACI_Login
          inputProperties: {
            }
      createEPG:
        type: REST
        input:
          action: post
          url: https://172.16.40.15/api/node/mo/uni/tn-${input.tenantName}/ap-${input.AppProfile}/epg-${input.EPGName}.json
          headers:
            Accept: application/json
            Content-Type: application/json
            cookie: APIC-Cookie=${Stage0.ACILogin.output.outputProperties.APIC-cookie}
          payload: |-
            {
             "fvAEPg": {
              "attributes": {
               "dn": "uni/tn-${input.tenantName}/ap-${input.AppProfile}/epg-${input.EPGName}",
               "prio": "level3",
               "name": "${input.EPGName}",
               "nameAlias": "${input.EPGAlias}",
               "descr": "${input.EPGDescription}",
               "rn": "epg-${input.EPGName}",
               "status": "created"
              },
              "children": [
               {
                "fvRsBd": {
                 "attributes": {
                  "tnFvBDName": "${input.BDname}",
                  "status": "created,modified"
                 },
                 "children": []
                }
               }
              ]
             }
            }
